<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:int="http://www.springframework.org/schema/integration"
	xmlns:oxm="http://www.springframework.org/schema/oxm"
	xmlns:int-http="http://www.springframework.org/schema/integration/http"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
						http://www.springframework.org/schema/beans/spring-beans.xsd
						http://www.springframework.org/schema/integration
						http://www.springframework.org/schema/integration/spring-integration.xsd
						http://www.springframework.org/schema/integration/http
						http://www.springframework.org/schema/integration/http/spring-integration-http.xsd
						http://www.springframework.org/schema/oxm
						http://www.springframework.org/schema/oxm/spring-oxm.xsd">

	<int:gateway
		service-interface="com.techhybris.alexa.integration.gateway.TestRestGateway"
		id="testRestGateway" />
	<int-http:outbound-gateway
		request-channel="testServiceRequestChannel"
		reply-channel="testServiceResponseChannel"
		url="https://httpbin.org/get" http-method="GET"
		expected-response-type="java.lang.String">

		<!-- Configured the Advice to validate the failure of rest call. -->
		<int-http:request-handler-advice-chain>
			<bean
				class="org.springframework.integration.handler.advice.ExpressionEvaluatingRequestHandlerAdvice">
				<property name="trapException" value="true" />
				<property name="onFailureExpression"
					value="#exception.cause.message" />
				<property name="failureChannel" ref="oauth2FailureChannel" />
			</bean>
		</int-http:request-handler-advice-chain>
	</int-http:outbound-gateway>
	<int:channel id="testServiceResponseChannel" />

</beans>						